---
- name: create a non-root user with sudo rights
  hosts: all
  remote_user: root
  tasks:

  - name: update aptitude cache
    raw: apt-get update

  - name: install python-apt for ansible
    raw: apt-get install python-apt

  - name: ensure a sudo group exists
    group: name=sudo state=present

  - name: ensure users in the sudo group can sudo passwordless
    lineinfile: "dest=/etc/sudoers state=present
                 regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD: ALL'
                 validate='visudo -cf %s'"

  - name: create the user account
    user: name={{ username }} state=present
          append=true group=sudo

  - name: install your public key
    authorized_key: user={{ username }} state=present
                    key={{ lookup('file', local_ssh_pubkey) }}

  - name: synchronize the known_hosts file.
    copy: src=~/.ssh/known_hosts dest={{ home }}/.ssh/known_hosts
          owner={{ username }} group={{ username }} mode=0644

  - name: some basic apt stuff
    apt: pkg={{ item }} state=installed
         update_cache=yes cache_valid_time=3600
    with_items:
    - git
    - vim
    - libxslt1-dev

- name: install devstack
  hosts: all
  vars_files:
  - customize.yml
  remote_user: "{{ username }}"
  tasks:

  - name: clone devstack
    git: repo=https://github.com/openstack-dev/devstack.git
         dest=~/devstack
         version={{ branch }}

  - name: devstack local.conf
    template: src=templates/devstack-local.conf.j2
              dest=~/devstack/local.conf

  - name: stack it
    command: chdir=~/devstack ./stack.sh

  - name: reinstall cinder's requirements
    command: pip install --upgrade -r /opt/stack/cinder/requirements.txt

  - name: unstack it
    command: chdir=~/devstack ./unstack.sh

  - name: restack it
    command: chdir=~/devstack ./stack.sh
